---
- name: 'Extract address of the node for Consul'
  uri:
    url: 'http://localhost:{{ nim_waku_rpc_tcp_port }}/'
    method: POST
    body: 
      method: 'get_waku_v2_debug_v1_info'
      params: []
      jsonrpc: '2.0'
      id: 1
    status_code: 200
    body_format: json
  register: waku_info
  ignore_errors: true

- name: Verify we got the node address
  assert:
    that: 'waku_info.json.result.listenStr is defined'
    fail_msg: 'Did not receive Nim-Waku node address!'
    quiet: true

- name: Extract peer ID from RPC response
  set_fact:
    nim_waku_peer_id: '{{ waku_info.json.result.listenStr.split("/") | last }}'

- name: Define Consul services
  set_fact:
    consul_services:
      - id: '{{ nim_waku_cont_name }}'
        name: '{{ nim_waku_cont_name }}'
        port: '{{ nim_waku_p2p_tcp_port }}'
        address: '{{ nim_waku_p2p_tcp_port }}'
        tags: ['{{ env }}.{{ stage }}', 'nim', 'waku']
        meta:
          node_enode: '{{ waku_info.json.result.listenStr | default("unknown") }}'
        checks:
          - name: '{{ nim_waku_cont_name }}-health'
            type: 'tcp'
            tcp: 'localhost:{{ nim_waku_p2p_tcp_port }}'

      - id: '{{ nim_waku_cont_name }}-metrics'
        name: '{{ nim_waku_cont_name }}-metrics'
        port: '{{ nim_waku_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nim', 'waku', 'metrics']
        meta:
          container: '{{ nim_waku_cont_name }}'
        checks:
          - name: 'beacon-node-metrics-health'
            type: 'http'
            http: 'http://localhost:{{ nim_waku_metrics_port }}/metrics'

      - id: '{{ nim_waku_cont_name }}-rpc'
        name: '{{ nim_waku_cont_name }}-rpc'
        port: '{{ nim_waku_rpc_tcp_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nim', 'waku', 'rpc']
        checks:
          - id: '{{ nim_waku_cont_name }}-rpc-health'
            type: 'script'
            script: '{{ nim_waku_cont_vol }}/rpc.sh get_waku_v2_debug_v1_info'

      - id: '{{ nim_waku_cont_name }}-websocket'
        name: '{{ nim_waku_cont_name }}-websocket'
        port: '{{ nim_waku_websockify_cont_port }}'
        address: '{{ nim_waku_p2p_tcp_port }}'
        tags: ['{{ env }}.{{ stage }}', 'nim', 'waku', 'websocket']
        meta:
          node_enode: '/dns4/{{ nim_waku_websockify_domain | mandatory }}/tcp/{{ nim_waku_websockify_cont_port }}/wss/p2p/{{ nim_waku_peer_id }}'
        checks:
          - name: '{{ nim_waku_cont_name }}-websocket-health'
            type: 'script'
            script: 'websocat -vk1E wss://localhost:{{ nim_waku_websockify_cont_port }}'

- name: Remove Websockify Consul service
  set_fact:
    consul_services: |
      {{ consul_services | rejectattr('name', 'match', '.*-websocket$') | list }}
  when: not nim_waku_websockify_enabled

- name: 'Consul service definition - {{ nim_waku_cont_name }}'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ nim_waku_cont_name | replace("-", "_") }}'
