---
- name: Install docker-compose package
  apt:
    name: docker-compose

- name: Install Python docker-compose library
  pip:
    name: docker-compose

- name: Download Websocat installed
  get_url:
    url: 'https://github.com/vi/websocat/releases/download/v1.8.0/websocat_1.8.0_newer_amd64.deb'
    dest: '/tmp/websocat_1.8.0_newer_amd64.deb'
    checksum: 'sha256:5968a3a2ede69fa8bb3df1419b908575f6532ce4eef250e1fcfbaadada3ccaef'

- name: Install Websocat utility for Websockets
  apt:
    deb: '/tmp/websocat_1.8.0_newer_amd64.deb'
