---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul", field="encryption-key")}}'
bootstarp__consul_agent_acl_token: '{{lookup("bitwarden", "consul", field="agent-acl-token")}}'
# Wireguard
wireguard_consul_acl_token: '{{lookup("bitwarden", "consul", field="wireguard-acl-token")}}'

# general container config
cont_state: started
cont_recreate: false
cont_restart: false

# SWAP
swap_file_size_mb: 2048

# Certbot renewal
certbot_containers_to_stop: ['websockify']
