---
# Tag dependent on fleet: test, prod
nim_waku_cont_tag: 'deploy-v2-{{ stage }}'
nim_waku_cont_name: 'nim-waku-v2'

nim_waku_p2p_tcp_port: 30303
nim_waku_p2p_udp_port: 30303

# Enable WebSockets via Websockify
nim_waku_websockify_enabled: true
nim_waku_websockify_proxy_enabled: true
nim_waku_websockify_cont_port: 443

# Open LibP2P Ports
open_ports_default_comment: 'Nim-Waku-V2'
open_ports_default_action: 'insert'
open_ports_default_chain: 'DOCKER-USER'
open_ports_list:
  - { port: '{{ nim_waku_p2p_tcp_port }}',         protocol: 'tcp' }
  - { port: '{{ nim_waku_p2p_udp_port }}',         protocol: 'udp' }
  - { port: '{{ nim_waku_websockify_cont_port }}', protocol: 'tcp', chain: 'INPUT', action: 'append'}
