---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: a51317d65e30ca9609778619195df96c8d05ba42
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 49757eacbb3840d3c03ae159baec96b2c3492682
  scm: git

- name: infra-role-matterbridge
  src: git@github.com:status-im/infra-role-matterbridge.git
  version: 10f34e0c677d16403e2a1f5e7e67a3d7b642e9cf
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 87f4498f90f0cbb66a1ddb425e8953b04ced1891
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: ba9d44e145f0aff75147eb26e7724e70ed35dcfd
  scm: git
